### PR TITLE
Basic Functionalities Complete

### PR DESCRIPTION
**Pull request by Prakhar314**
# **Current UI**
home
scan

### **Note**

- The settings button on the top left doesn't do anything right now.
- Errors, if any, are displayed in place of text.
- Images are resized to max 500 by 500 px on capture/upload.

### CODE REVIEW

**Comment by Aman-zishan** [comment]
Awesome ✨

**Comment by Aman-zishan** [comment]
Let the settings button leave as it is, Ill add a drawer to it

**Comment by Prakhar314** [comment]
Thanks.
Actually, I am participating in hacktoberfest. So I would appreciate it if you could add "hacktoberfest-accepted" label to this PR.

**Comment by Aman-zishan** [comment]
Yeah sure, anyways since your PR is merged its fine. I have added a topic to this repo

**Pull request merged**
